import { NextPage } from "next";
import Head from "next/head";
import Carousel from "@/components/Slider";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import Banner from "@/components/Banner";
import Luxury from "@/components/Luxury";
import Cards from "@/components/Cards";
import Riezel from "@/components/Riezel";
import Testimonial from "@/components/Testimonial";
import Contact from "@/components/Contact";
import News from "@/components/News";
import Work from "@/components/Work";

const Index: NextPage = () => {
  return (
    <>
      <Head>
        <script
          src="https://kit.fontawesome.com/e7cf70af4d.js"
          crossOrigin="anonymous"
        ></script>
        <title>property</title>
        <meta name="description" content="Generated by Create Next Stack." />
      </Head>

      <Navbar />
      <Banner />
      <Luxury />
      <Cards />
      <Riezel />
      <Testimonial />
      <Carousel />
      <Contact />
      <News />
      <Work />
      <Footer />
    </>
  );
};

export default Index;
